name: Build Contract

on:
  push:
    branches: ['**']

env:
  SINGLE_ASSET_REWARD: "--manifest-path=src/contracts/single_asset_reward/Cargo.toml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ env.SINGLE_ASSET_REWARD }} -- -D warnings

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ env.SINGLE_ASSET_REWARD }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ env.SINGLE_ASSET_REWARD }}